name: flexi_text
description: A responsive and flexible Flutter Text widget with dynamic font scaling for mobile, tablet, and desktop.
version: 0.0.3
homepage: https://github.com/MgThiha-Coding/Flexi_Text
repository: https://github.com/MgThiha-Coding/Flexi_Text.git
documentation: https://github.com/MgThiha-Coding/Flexi_Text#readme
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
